name: Deklaracja opracowania pytania
description: Zadeklaruj pytanie, które chcesz opracować
title: '[Opracowanie]: (Katedra) (Numer pytania) Treść pytania'
labels: ['Opracowanie']
body:
  - type: markdown
    attributes:
      value: Dziękujemy za chęć pracy!
  - type: textarea
    id: description
    attributes:
      label: Lokacja pracy
      description: Gdzie możemy znaleźć Twoje opracowanie, skąd będzie merge do głównej gałęzi?
      placeholder: Może być nazwa brancha (jeśli w tym samym repozytorium) lub link do brancha w forkowanym repozytorium.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checklista
      description: Upewnijmy się, że to zgłoszenie jest ważne!
      options:
        - label: "\"Contribution guidelines\" zostały przeze mnie przeczytane i je akceptuję."
          required: true
        - label: "Zaznaczam wszystkie pola bez ich przeczytania."
          required: false
        - label: "Upewniłem/am się że pytanie, które chcę opracować, nie jest już opracowywane przez kogoś innego."
          required: true